# Generated by Django 6.0.2 on 2026-02-12 05:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_tasklist_remove_task_todo_list_task_task_list_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='app.tasklist'),
        ),
    ]
